repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies: ["pep8-naming==0.12.1", "flake8-bugbear==22.1.11"]
            args: [--config=etc/python/setup.cfg]
            files: ^.*/python/.*$
    # # https://pylint.pycqa.org/en/latest/user_guide/pre-commit-integration.html
    # - repo: https://github.com/pycqa/pylint
    #   rev: v2.12.2
    #   hooks:
    #       - id: pylint
    #         language: system
    #         args: [--rcfile=backend/pyproject.toml]
    #         files: ^.*/python/.*$
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.5.1
      hooks:
          - id: prettier
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.6.0
      hooks:
          - id: eslint
            files: \.[jt]s?$ # *.js, *.ts
            types: [file]
            additional_dependencies:
                - eslint@8.6.0
                - typescript@4.5.4
                - "@typescript-eslint/eslint-plugin@5.9.0"
                - "@typescript-eslint/parser@5.9.0"
                - eslint-config-prettier@8.3.0
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: master
      hooks:
          - id: go-fmt
