repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
      - id: pylint
        language: system
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.6.0
    hooks:
      - id: eslint
        files: \.[jt]s?$ # *.js, *.ts
        types: [file]
        additional_dependencies:
          - eslint@8.6.0
          - typescript@4.5.4
          - "@typescript-eslint/eslint-plugin@5.9.0"
          - "@typescript-eslint/parser@5.9.0"
          - eslint-config-prettier@8.3.0
